Repository flow-project/flow, pull requests merged in 2018-12, with the labels that each got.

#256 Base env cleanup
  flow/envs/base_env.py
  flow/envs/multiagent_env.py
Labels: kernel

#248 Tests rewards
  flow/core/rewards.py
  flow/envs/green_wave_env.py
  tests/fast_tests/test_rewards.py
Labels: software safety

#253 Kernel abstractions
  flow/core/kernel/__init__.py
  flow/core/kernel/kernel.py
  flow/core/kernel/scenario/__init__.py
  flow/core/kernel/scenario/base.py
  flow/core/kernel/simulation/__init__.py
  flow/core/kernel/simulation/base.py
  flow/core/kernel/traffic_light/__init__.py
  flow/core/kernel/traffic_light/base.py
  flow/core/kernel/vehicle/__init__.py
  flow/core/kernel/vehicle/base.py
Labels: kernel

#254 Vehicle params
  examples/rllab/cooperative_merge.py
  examples/rllab/figure_eight.py
  examples/rllab/green_wave.py
  examples/rllab/stabilizing_highway.py
  examples/rllab/velocity_bottleneck.py
  examples/rllib/cooperative_merge.py
  examples/rllib/figure_eight.py
  examples/rllib/green_wave.py
  examples/rllib/multiagent_exps/multiagent_figure_eight.py
  examples/rllib/stabilizing_highway.py
  examples/rllib/velocity_bottleneck.py
  examples/sumo/bay_bridge.py
  examples/sumo/bay_bridge_toll.py
  examples/sumo/bottlenecks.py
  examples/sumo/figure_eight.py
  examples/sumo/loop_merge.py
  examples/sumo/merge.py
  examples/sumo/minicity.py
  flow/benchmarks/baselines/bottleneck0.py
  flow/benchmarks/baselines/bottleneck1.py
  flow/benchmarks/baselines/bottleneck2.py
  flow/benchmarks/baselines/figureeight012.py
  flow/benchmarks/bottleneck0.py
  flow/benchmarks/bottleneck1.py
  flow/benchmarks/bottleneck2.py
  flow/benchmarks/figureeight0.py
  flow/benchmarks/figureeight1.py
  flow/benchmarks/figureeight2.py
  flow/benchmarks/grid0.py
  flow/benchmarks/grid1.py
  flow/benchmarks/merge0.py
  flow/benchmarks/merge1.py
  flow/benchmarks/merge2.py
  flow/core/params.py
  flow/core/vehicles.py
  flow/envs/bottleneck_env.py
  flow/envs/green_wave_env.py
  tests/data/rllib_data/multi_agent/params.json
  tests/data/rllib_data/single_agent/params.json
  tests/fast_tests/test_collisions.py
  tests/fast_tests/test_experiment_base_class.py
  tests/fast_tests/test_two_loops_one_merging.py
  tests/fast_tests/test_util.py
  tests/fast_tests/test_vehicles.py
  tests/setup_scripts.py
Labels: kernel

#303 added action clipping for rewards
  .travis.yml
  flow/core/rewards.py
  flow/envs/base_env.py
  flow/envs/multiagent_env.py
Labels: bug

#319 Travis fix
  .travis.yml
  flow/core/rewards.py
Labels: bug, high priority

#315 added test for reset in bottleneck env
  tests/fast_tests/test_environments.py
Labels: software safety

#314 added test for wave attenuation reset
  tests/fast_tests/test_environments.py
Labels: software safety

#312 added a get_type method to the vehicles class
  flow/core/vehicles.py
  flow/envs/base_env.py
  flow/envs/green_wave_env.py
  flow/scenarios/base_scenario.py
  flow/scenarios/loop_merge.py
Labels: kernel

#311 Sumo exp cleanup
  examples/sumo/bay_bridge.py
  examples/sumo/bay_bridge_toll.py
  examples/sumo/bottlenecks.py
  examples/sumo/figure_eight.py
  examples/sumo/grid.py
  examples/sumo/highway.py
  examples/sumo/loop_merge.py
  examples/sumo/merge.py
  examples/sumo/minicity.py
  examples/sumo/sugiyama.py
  flow/benchmarks/baselines/bottleneck0.py
  flow/benchmarks/baselines/bottleneck1.py
  flow/benchmarks/baselines/bottleneck2.py
  flow/benchmarks/baselines/figureeight012.py
  flow/benchmarks/baselines/grid0.py
  flow/benchmarks/baselines/grid1.py
  flow/benchmarks/baselines/merge012.py
  flow/core/experiment.py
  flow/utils/leaderboard/evaluate.py
  tests/fast_tests/test_bottleneck.py
  tests/fast_tests/test_collisions.py
  tests/fast_tests/test_controllers.py
  tests/fast_tests/test_experiment_base_class.py
  tests/fast_tests/test_green_wave.py
  tests/fast_tests/test_traffic_lights.py
  tests/fast_tests/test_two_loops_one_merging.py
  tests/slow_tests/test_benchmarks.py
  tutorials/tutorial01_sumo.ipynb
  tutorials/tutorial03_rllab.ipynb
  tutorials/tutorial05_scenarios.ipynb
  tutorials/tutorial06_environments.ipynb
  tutorials/tutorial08_traffic_lights.ipynb
  tutorials/tutorial09_inflows.ipynb
  tutorials/tutorial11_rllab_ec2.ipynb
Labels: kernel

#281 Kernel simulation
  flow/core/kernel/kernel.py
  flow/core/kernel/simulation/__init__.py
  flow/core/kernel/simulation/traci.py
  flow/envs/base_env.py
  flow/envs/multiagent_env.py
  tests/fast_tests/test_environment_base_class.py
Labels: kernel

#313 removed a redundant test
  tests/fast_tests/test_bottleneck.py
  tests/setup_scripts.py
Labels: software safety

#320 Scenario compatibility
  flow/scenarios/base_scenario.py
  flow/scenarios/bottleneck.py
  flow/scenarios/figure_eight.py
  flow/scenarios/grid.py
  flow/scenarios/highway.py
  flow/scenarios/loop.py
  flow/scenarios/loop_merge.py
  flow/scenarios/merge.py
  flow/scenarios/minicity.py
  flow/scenarios/multi_loop.py
  tests/setup_scripts.py
Labels: kernel

#310 Kernel traffic lights
  examples/rllab/green_wave.py
  examples/rllab/velocity_bottleneck.py
  examples/rllib/velocity_bottleneck.py
  examples/sumo/bay_bridge.py
  examples/sumo/bottlenecks.py
  examples/sumo/grid.py
  flow/benchmarks/baselines/bottleneck0.py
  flow/benchmarks/baselines/bottleneck1.py
  flow/benchmarks/baselines/bottleneck2.py
  flow/benchmarks/baselines/figureeight012.py
  flow/benchmarks/baselines/grid0.py
  flow/benchmarks/baselines/grid1.py
  flow/benchmarks/baselines/merge012.py
  flow/benchmarks/bottleneck0.py
  flow/benchmarks/bottleneck1.py
  flow/benchmarks/bottleneck2.py
  flow/benchmarks/rllab/trpo_runner.py
  flow/core/kernel/kernel.py
  flow/core/kernel/traffic_light/__init__.py
  flow/core/kernel/traffic_light/traci.py
  flow/core/params.py
  flow/core/traffic_lights.py
  flow/envs/base_env.py
  flow/envs/bottleneck_env.py
  flow/envs/green_wave_env.py
  flow/envs/multiagent_env.py
  flow/scenarios/base_scenario.py
  flow/scenarios/bottleneck.py
  flow/scenarios/figure_eight.py
  flow/scenarios/grid.py
  flow/scenarios/highway.py
  flow/scenarios/loop.py
  flow/scenarios/loop_merge.py
  flow/scenarios/merge.py
  flow/scenarios/minicity.py
  flow/scenarios/multi_loop.py
  flow/scenarios/netfile.py
  flow/scenarios/openstreetmap.py
  flow/utils/leaderboard/evaluate.py
  flow/utils/registry.py
  flow/utils/rllib.py
  tests/fast_tests/test_traffic_lights.py
  tests/fast_tests/test_util.py
  tests/setup_scripts.py
  tutorials/tutorial01_sumo.ipynb
  tutorials/tutorial02_rllib.ipynb
  tutorials/tutorial03_rllab.ipynb
  tutorials/tutorial08_traffic_lights.ipynb
Labels: kernel

#328 replaced SumoExperiment with Experiment
  examples/sumo/bay_bridge.py
  examples/sumo/bay_bridge_toll.py
  examples/sumo/bottlenecks.py
  examples/sumo/figure_eight.py
  examples/sumo/grid.py
  examples/sumo/highway.py
  examples/sumo/loop_merge.py
  examples/sumo/merge.py
  examples/sumo/minicity.py
  examples/sumo/sugiyama.py
  flow/benchmarks/baselines/bottleneck0.py
  flow/benchmarks/baselines/bottleneck1.py
  flow/benchmarks/baselines/bottleneck2.py
  flow/benchmarks/baselines/figureeight012.py
  flow/benchmarks/baselines/grid0.py
  flow/benchmarks/baselines/grid1.py
  flow/benchmarks/baselines/merge012.py
  flow/core/experiment.py
  flow/utils/leaderboard/evaluate.py
  tests/fast_tests/test_collisions.py
  tests/fast_tests/test_controllers.py
  tests/fast_tests/test_experiment_base_class.py
  tests/fast_tests/test_green_wave.py
  tests/fast_tests/test_traffic_lights.py
  tests/fast_tests/test_two_loops_one_merging.py
  tutorials/tutorial01_sumo.ipynb
  tutorials/tutorial05_scenarios.ipynb
  tutorials/tutorial06_environments.ipynb
  tutorials/tutorial09_inflows.ipynb
Labels: kernel

#341 Cf lc params abstractions
  examples/rllab/cooperative_merge.py
  examples/rllab/figure_eight.py
  examples/rllab/green_wave.py
  examples/rllab/stabilizing_highway.py
  examples/rllab/velocity_bottleneck.py
  examples/rllib/cooperative_merge.py
  examples/rllib/figure_eight.py
  examples/rllib/green_wave.py
  examples/rllib/multiagent_exps/multiagent_figure_eight.py
  examples/rllib/stabilizing_highway.py
  examples/rllib/velocity_bottleneck.py
  examples/sumo/bay_bridge.py
  examples/sumo/bay_bridge_toll.py
  examples/sumo/bottlenecks.py
  examples/sumo/figure_eight.py
  examples/sumo/loop_merge.py
  examples/sumo/merge.py
  examples/sumo/minicity.py
  flow/benchmarks/baselines/bottleneck0.py
  flow/benchmarks/baselines/bottleneck1.py
  flow/benchmarks/baselines/bottleneck2.py
  flow/benchmarks/baselines/figureeight012.py
  flow/benchmarks/bottleneck0.py
  flow/benchmarks/bottleneck1.py
  flow/benchmarks/bottleneck2.py
  flow/benchmarks/figureeight0.py
  flow/benchmarks/figureeight1.py
  flow/benchmarks/figureeight2.py
  flow/benchmarks/grid0.py
  flow/benchmarks/grid1.py
  flow/benchmarks/merge0.py
  flow/benchmarks/merge1.py
  flow/benchmarks/merge2.py
  flow/controllers/__init__.py
  flow/controllers/base_controller.py
  flow/controllers/car_following_models.py
  flow/controllers/lane_change_controllers.py
  flow/controllers/rlcontroller.py
  flow/controllers/velocity_controllers.py
  flow/core/vehicles.py
  flow/envs/bottleneck_env.py
  flow/envs/green_wave_env.py
  flow/utils/rllib.py
  tests/data/rllib_data/multi_agent/params.json
  tests/data/rllib_data/single_agent/params.json
  tests/fast_tests/test_collisions.py
  tests/fast_tests/test_controllers.py
  tests/fast_tests/test_environment_base_class.py
  tests/fast_tests/test_experiment_base_class.py
  tests/fast_tests/test_traffic_lights.py
  tests/fast_tests/test_two_loops_one_merging.py
  tests/fast_tests/test_util.py
  tests/fast_tests/test_vehicles.py
  tests/setup_scripts.py
  tutorials/tutorial07_controllers.ipynb
Labels: kernel

#343 created objects that are used when passing data from aimsun
  flow/utils/aimsun/struct.py
Labels: aimsun

#316 converted gen_custom_start_pos to a staticmethod
  examples/rllab/green_wave.py
  examples/rllib/green_wave.py
  examples/sumo/grid.py
  flow/benchmarks/grid0.py
  flow/benchmarks/grid1.py
  flow/scenarios/base_scenario.py
  flow/scenarios/grid.py
  flow/scenarios/highway.py
  flow/scenarios/loop_merge.py
  flow/scenarios/multi_loop.py
  tests/setup_scripts.py
Labels: kernel

#325 Remove make routes
  .gitignore
  flow/core/experiment.py
  flow/core/params.py
  flow/envs/base_env.py
  flow/envs/green_wave_env.py
  flow/envs/multiagent_env.py
  flow/scenarios/base_scenario.py
  flow/scenarios/grid.py
  flow/scenarios/highway.py
  flow/scenarios/loop_merge.py
  flow/scenarios/multi_loop.py
  tests/data/rllib_data/multi_agent/params.json
  tests/data/rllib_data/single_agent/params.json
  tests/fast_tests/test_collisions.py
  tests/fast_tests/test_environment_base_class.py
  tests/fast_tests/test_environments.py
  tests/fast_tests/test_green_wave.py
  tests/fast_tests/test_scenario_base_class.py
  tests/fast_tests/test_traffic_lights.py
  tests/setup_scripts.py
Labels: kernel

#344 Aimsun install
  docs/source/flow_setup.rst
  flow/config.py
  flow/core/kernel/simulation/traci.py
  scripts/setup_aimsun.sh
Labels: aimsun
