Repository flow-project/flow, pull requests merged in 2019-05, with the labels that each got.

#512 new tests to visualizers
  flow/visualize/capacity_diagram_generator.py
  tests/fast_tests/test_files/inflows_outflows.csv
  tests/fast_tests/test_visualizers.py
Labels: software safety

#507 added test for osm files
  tests/data/euclid.osm
  tests/fast_tests/test_scenario_base_class.py
Labels: software safety

#525 New pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: git workflow

#521 Better name for 'self.last_change' array
  flow/envs/green_wave_env.py
  tutorials/tutorial11_traffic_lights.ipynb
Labels: documentation, enhancement

#527 added template for tutorials
  tutorials/img/template_img.png
  tutorials/img/tutorials_readme.png
  tutorials/img/tutorials_website.png
  tutorials/tutorialxx_template.ipynb
Labels: documentation
