Repository flow-project/flow, pull requests merged in 2019-08, with the labels that each got.

#654 Exception handling
  flow/core/kernel/vehicle/traci.py
  flow/envs/base_env.py
  flow/multiagent_envs/multiagent_env.py
Labels: enhancement

#677 Missing matplotlib in conda setup
  environment.yml
Labels: bug

#629 Fix vehicle accounting (for multi-agent settings)
  flow/core/kernel/vehicle/traci.py
Labels: bug

#692 removed redundant tutorials
  tutorials/tutorial06_osm.ipynb
  tutorials/tutorial07_network_templates.ipynb
  tutorials/tutorial07_osm.ipynb
  tutorials/tutorial08_network_templates.ipynb
  tutorials/tutorial10_traffic_lights.ipynb
  tutorials/tutorial11_traffic_lights.ipynb
Labels: cleaning

#642 Improving Traffic Light Tutorial
  README.md
  flow/envs/green_wave_env.py
  tutorials/tutorial10_traffic_lights.ipynb
Labels: cleaning
