Repository flow-project/flow, pull requests merged in 2019-06, with the labels that each got.

#532 Simplified PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, git workflow

#528 Update Readme with Stack Overflow tag information
  README.md
Labels: enhancement

#535 Add explanation on how to fix a bug when first installing flow
  tutorials/README.md
Labels: bug fix, tutorial

#539 Remove obsolete features from grid environment
  flow/envs/green_wave_env.py
  tests/fast_tests/test_green_wave.py
Labels: cleaning

#533 extended test coverage for grid examples
  examples/rllib/green_wave.py
  examples/sumo/grid.py
  tests/fast_tests/test_examples.py
Labels: software safety

#541 Remove obsolete features from bottleneck environment
  flow/envs/bottleneck_env.py
  tests/fast_tests/test_environments.py
Labels: cleaning

#531 Scripting API for Aimsun
  .coveragerc
  .gitignore
  flow/utils/aimsun/Aimsun_Flow.ang
  flow/utils/aimsun/generate.py
  flow/utils/aimsun/load.py
  flow/utils/aimsun/scripting_api.py
  tests/fast_tests/test_aimsun_scripting_api.py
Labels: aimsun, enhancement

#530 Remove loop merge
  examples/rllab/cooperative_merge.py
  examples/rllib/cooperative_merge.py
  flow/envs/__init__.py
  flow/envs/loop/loop_merges.py
  flow/scenarios/loop_merge.py
  tests/fast_tests/test_environments.py
  tests/fast_tests/test_two_loops_one_merging.py
Labels: cleaning

#524 New router
  flow/controllers/routing_controllers.py
  flow/core/kernel/scenario/traci.py
  flow/core/kernel/vehicle/traci.py
  flow/core/params.py
  flow/scenarios/base_scenario.py
  flow/scenarios/bay_bridge.py
  tests/fast_tests/test_environments.py
  tests/fast_tests/test_scenario_base_class.py
  tutorials/tutorial06_scenarios.ipynb
Labels: new feature

#554 Fix emission path bug
  flow/core/experiment.py
  tests/fast_tests/test_examples.py
  tutorials/README.md
  tutorials/tutorial01_sumo.ipynb
Labels: bug fix, sumo
