Repository flow-project/flow, pull requests merged in 2019-07, with the labels that each got.

#585 Ease installation of Flow for OSX
  scripts/setup_sumo_osx.sh
Labels: enhancement

#575 Simplify grid scenario
  flow/core/kernel/scenario/traci.py
  flow/envs/green_wave_env.py
  flow/scenarios/grid.py
  tests/fast_tests/test_traffic_lights.py
Labels: enhancement

#576 updates to tutorial
  flow/core/kernel/simulation/traci.py
  tutorials/tutorial01_sumo.ipynb
Labels: bug, documentation

#586 Added template for Issues (Bug, Feature, Question)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/issues.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cleaning, enhancement

#602 Code typo in tutorial (quick fix)
  tutorials/tutorial09_environments.ipynb
Labels: bug

#604 Delete temporary files after loading an Aimsun template
  flow/core/kernel/scenario/aimsun.py
Labels: cleaning

#594 issue 42
  .travis.yml
  docs/mathparse.py
  docs/source/conf.py
  examples/rllab/__init__.py
  examples/rllab/green_wave.py
  examples/rllib/__init__.py
  examples/rllib/cooperative_merge.py
  examples/rllib/figure_eight.py
  examples/rllib/multiagent_exps/__init__.py
  examples/rllib/multiagent_exps/multiagent_figure_eight.py
  examples/rllib/multiagent_exps/multiagent_stabilizing_the_ring.py
  examples/rllib/stabilizing_highway.py
  examples/rllib/stabilizing_the_ring.py
  examples/rllib/velocity_bottleneck.py
  examples/sumo/__init__.py
  examples/sumo/bottlenecks.py
  examples/sumo/density_exp.py
  examples/sumo/minicity.py
  flow/core/kernel/vehicle/aimsun.py
  flow/envs/bay_bridge/__init__.py
  flow/envs/bay_bridge/base.py
  flow/envs/loop/wave_attenuation.py
  flow/multiagent_envs/loop/__init__.py
  flow/utils/aimsun/generate.py
  flow/utils/aimsun/load.py
  flow/utils/aimsun/run.py
  flow/utils/aimsun/scripting_api.py
  flow/visualize/plot_ray_results.py
  scripts/sync_s3.py
  setup.py
  tests/dummy_server.py
Labels: cleaning, documentation

#587 RLlib visualizer tweaks
  flow/visualize/visualizer_rllib.py
  tests/fast_tests/test_visualizers.py
Labels: enhancement

#630 Minor changes to RLlib visualizer
  flow/visualize/visualizer_rllib.py
Labels: bug, documentation, enhancement

#607 final 0.4.0 commit
  examples/rllab/stabilizing_the_ring.py
  examples/rllib/stabilizing_the_ring.py
  examples/sumo/sugiyama.py
  flow/core/params.py
  flow/version.py
  scripts/setup_sumo_osx.sh
  scripts/setup_sumo_ubuntu1404.sh
  scripts/setup_sumo_ubuntu1604.sh
  scripts/setup_sumo_ubuntu1804.sh
  setup.py
  tests/fast_tests/test_scenario_base_class.py
  tests/fast_tests/test_vehicles.py
Labels: upgrade

#623 Multi-agent traffic light grid
  docs/source/multiagent.rst
  examples/rllib/multiagent_exps/multiagent_traffic_light_grid.py
  flow/envs/green_wave_env.py
  flow/multiagent_envs/__init__.py
  flow/multiagent_envs/traffic_light_grid.py
  tests/fast_tests/test_examples.py
  tests/fast_tests/test_green_wave.py
  tests/setup_scripts.py
Labels: enhancement

#584 added Linear Adaptive Controller
  flow/controllers/__init__.py
  flow/controllers/car_following_models.py
  flow/controllers/velocity_controllers.py
  tests/fast_tests/test_controllers.py
Labels: enhancement

#649 add common error fix to tutorials README
  tutorials/README.md
Labels: documentation

#647 Quick fix grid scenario
  flow/scenarios/grid.py
Labels: bug

#658 Add "avg_delay_specified_vehicles" to rewards.py
  flow/core/rewards.py
Labels: enhancement

#662 delete xml emission files if creating csv versions of them
  flow/core/experiment.py
  flow/visualize/visualizer_rllib.py
  tests/fast_tests/test_experiment_base_class.py
Labels: cleaning
