Repository flow-project/flow, pull requests merged in 2020-01, with the labels that each got.

#802 Update tutorials to match with the new way of running experiments
  .coveragerc
  docs/source/index.rst
  examples/exp_configs/non_rl/aimsun_template.py
  tutorials/README.md
  tutorials/tutorial01_sumo.ipynb
  tutorials/tutorial02_aimsun.ipynb
  tutorials/tutorial03_rllib.ipynb
  tutorials/tutorial04_visualize.ipynb
  tutorials/tutorial05_networks.ipynb
  tutorials/tutorial06_osm.ipynb
  tutorials/tutorial07_network_templates.ipynb
  tutorials/tutorial08_environments.ipynb
  tutorials/tutorial11_inflows.ipynb
  tutorials/tutorial12_bottlenecks.ipynb
Labels: documentation

#758 added plotly 2.4.0 dependency
  environment.yml
  requirements.txt
Labels: bug

#757 remove remaining rllab
  .coveragerc
  docs/source/conf.py
  tests/fast_tests/test_visualizers.py
  tutorials/README.md
  tutorials/tutorial00_flow.ipynb
  tutorials/tutorial01_sumo.ipynb
  tutorials/tutorial02_aimsun.ipynb
  tutorials/tutorial04_visualize.ipynb
  tutorials/tutorial05_networks.ipynb
  tutorials/tutorial06_osm.ipynb
  tutorials/tutorial07_network_templates.ipynb
  tutorials/tutorial08_environments.ipynb
  tutorials/tutorial09_controllers.ipynb
  tutorials/tutorial10_traffic_lights.ipynb
  tutorials/tutorial11_inflows.ipynb
  tutorials/tutorial12_bottlenecks.ipynb
Labels: bug, cleaning
